version: "3.8"
services:
  main:
    container_name: main
    build: 
      dockerfile: Dockerfile
      context: .
      target: development
    depends_on:
      - mongodb
    restart: always
    ports:
      - "8080:3000"
    volumes:
      - /home/jazmin/Drives/DATOS/Documents/Repos/test-api-nest/
    
      
  mongodb:
    image: mongo
    container_name: mongo1
    volumes:
      - /home/jazmin/mongodb/mongo-volume:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_DATABASE=thedbname
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root 

  mongo-express:
    links:
    - mongodb
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment: 
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER="mongo1"

networks:
  default:
    name: mongodb_network
